exclude: '^$'
fail_fast: false
repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: end-of-file-fixer
    -   id: check-shebang-scripts-are-executable
    -   id: detect-private-key
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--indent', '2', '--no-sort-keys']
        exclude: ^Pipfile
    -   id: check-yaml
        exclude: ^charts/
    -   id: check-toml

# commit messages
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
    -   id: commitizen
        stages: [commit-msg]

# Markdown tools
-   repo: https://github.com/rvben/rumdl-pre-commit
    rev: v0.0.172 # Use the latest release tag
    hooks:
    -   id: rumdl
        # To automatically fix issues:
        args: [--fix]

# Python tools
-   repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.14.4
    hooks:
    # Run the linter.
    -   id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
    # Run the formatter.
    -   id: ruff-format

# Shell script tools
-   repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
    -   id: shell-fmt-go
        args:
        -   -i
        -   "2"

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck

# Security tools
-   repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.490' # change to tag or sha
    hooks:
    -   id: checkov_diff
        args:
        -   '--skip-check'
        -   'CKV_DOCKER_2,CKV_SECRET_6'
        -   '--quiet'
        -   '-f' # required and must come last
    -   id: checkov_secrets
        args:
        -   '--quiet'
        -   '-f' # required and must come last
